### ISSUE TITLE
Not working on visual studio 2022

### ISSUE THREAD

**Issue by ccaioccesar** [StefanKert/BuildVision#123] opened 2022-09-03 16:18 UTC
I'm getting this message after installing it on vs2022:

![image](https://user-images.githubusercontent.com/73500606/188279326-83c9f7c1-29a8-4830-96a0-af65d9f9092a.png)

I tested on two different machines (win10), the second one is a clean installation of vs22 without any third-party extension, and I got this message box on both.

Version 17.3.3

**Comment by StKuhn** [comment] 2022-09-10 07:12
Error message in Activity Log:
`<entry>
    <record>327</record>
    <time>2022/09/10 07:03:50.814</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [BuildVisionPackage]</description>
    <guid>{837C3C3B-8382-4839-9C9A-807B758A929F}</guid>
  </entry>
  <entry>
    <record>328</record>
    <time>2022/09/10 07:03:50.949</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [BuildVisionPackage]Source: &apos;Microsoft.VisualStudio.Validation&apos; Description: Cannot find an instance of the Microsoft.VisualStudio.Shell.Interop.IVsSolutionBuildManager5 service.&#x000D;&#x000A;</description>
    <guid>{837C3C3B-8382-4839-9C9A-807B758A929F}</guid>
    <hr>0x80131500</hr>
    <errorinfo></errorinfo>`

Adding Microsoft.VisualStudio.Shell.Interop.11.0.dll to gac did not solve it.

**Comment by michael-hawker** [comment] 2022-09-16 22:17
Duplicate of #120

**Comment by StefanKert** [comment] 2022-09-26 11:06
Hi folks,

as @michael-hawker stated this is a duplicate so I'll post an update there. Sorry for the delay.

**Closed by StefanKert** 2022-09-26 11:06 UTC
