### ISSUE TITLE
Projects Grid doesn't update after build

### ISSUE THREAD

**Issue by 3x71** [StefanKert/BuildVision#117] opened 2022-02-22 10:36 UTC
Visual Studio 2022 17.1.0, BuildVision 3.1.0

![example](https://user-images.githubusercontent.com/51165404/155113917-bfaa9a7a-cf82-4494-aa0e-a83d5afb299f.PNG)

**Comment by praktii** [comment] 2022-02-23 09:58
I've noticed, that the progressbar that should show the complete Buildprogress, i guess,  isnt updating aswell.

**Comment by gamagan** [comment] 2022-02-26 13:25
Running into these same issues.

**Comment by Graupner** [comment] 2022-03-06 23:01
VisualStudio 2019 Buildvision 3.1.0.7

1. Columns Warnings and Errors always empty (no Update)
2. Elapsed time of each project increases when a project is completed. 
3. Strange Version Number in Caption Bar

![BuildVision_VS2019](https://user-images.githubusercontent.com/20925581/156945781-a8620fb4-d4d2-4c01-abaa-1b6c47b07b50.png)

**Comment by Graupner** [comment] 2022-03-06 23:06
C:\Users\XXX\AppData\Local\BuildVision\extension.log

2022-03-06 23:56:56.133 [03552] EROR [01] SolutionBuildEvents       
System.NullReferenceException: Object reference not set to an instance of an object.
   at BuildVision.Core.BuildInformationProvider.GetProjectState(Boolean success, Boolean canceled, IProjectItem currentProject)
   at BuildVision.Core.BuildInformationProvider.ProjectBuildFinished(BuildAction buildAction, String projectIdentifier, Boolean success, Boolean canceled)
   at BuildVision.Core.SolutionBuildEvents.UpdateProjectCfg_Done(IVsHierarchy pHierProj, IVsCfg pCfgProj, IVsCfg pCfgSln, UInt32 dwAction, Int32 fSuccess, Int32 fCancel)
2022-03-06 23:57:35.619 [03552] EROR [01] SolutionBuildEvents       
System.NullReferenceException: Object reference not set to an instance of an object.
   at BuildVision.Core.BuildInformationProvider.GetProjectState(Boolean success, Boolean canceled, IProjectItem currentProject)
   at BuildVision.Core.BuildInformationProvider.ProjectBuildFinished(BuildAction buildAction, String projectIdentifier, Boolean success, Boolean canceled)
   at BuildVision.Core.SolutionBuildEvents.UpdateProjectCfg_Done(IVsHierarchy pHierProj, IVsCfg pCfgProj, IVsCfg pCfgSln, UInt32 dwAction, Int32 fSuccess, Int32 fCancel)
2022-03-06 23:57:37.713 [03552] EROR [01] SolutionBuildEvents       
System.NullReferenceException: Object reference not set to an instance of an object.
   at BuildVision.Core.BuildInformationProvider.GetProjectState(Boolean success, Boolean canceled, IProjectItem currentProject)
   at BuildVision.Core.BuildInformationProvider.ProjectBuildFinished(BuildAction buildAction, String projectIdentifier, Boolean success, Boolean canceled)
   at BuildVision.Core.SolutionBuildEvents.UpdateProjectCfg_Done(IVsHierarchy pHierProj, IVsCfg pCfgProj, IVsCfg pCfgSln, UInt32 dwAction, Int32 fSuccess, Int32 fCancel)
2022-03-06 23:58:00.653 [03552] EROR [01] SolutionBuildEvents       
System.NullReferenceException: Object reference not set to an instance of an object.
   at BuildVision.Core.BuildInformationProvider.GetProjectState(Boolean success, Boolean canceled, IProjectItem currentProject)
   at BuildVision.Core.BuildInformationProvider.ProjectBuildFinished(BuildAction buildAction, String projectIdentifier, Boolean success, Boolean canceled)
   at BuildVision.Core.SolutionBuildEvents.UpdateProjectCfg_Done(IVsHierarchy pHierProj, IVsCfg pCfgProj, IVsCfg pCfgSln, UInt32 dwAction, Int32 fSuccess, Int32 fCancel)

**Comment by aeris170** [comment] 2022-09-20 13:03
@StefanKert sorry for tagging you but could we get an update on this? The plugin is next to useless if this issue is not resolved.

**Comment by StefanKert** [comment] 2024-04-29 06:12
Hi there,

a Preview of version 4.x is available in the VSIX Gallery feed.  You can follow along with the installation instructions from the README https://github.com/StefanKert/BuildVision?tab=readme-ov-file#setup-visual-studio-for-preview-channel. Would love to hear if this fixes the issues you are facing. As soon as the issues that people are currently seeing are resolved there will be a official marketplace release.

Thanks :)

**Comment by aeris170** [comment] 2024-04-29 09:12
> Hi there,
> 
> a Preview of version 4.x is available in the VSIX Gallery feed.  You can follow along with the installation instructions from the README https://github.com/StefanKert/BuildVision?tab=readme-ov-file#setup-visual-studio-for-preview-channel. Would love to hear if this fixes the issues you are facing. As soon as the issues that people are currently seeing are resolved there will be a official marketplace release.
> 
> Thanks :) 

Hey Stefan! I'll give it a try and report back tonight. Can't do it now because I'm away.

**Comment by StefanKert** [comment] 2024-05-02 04:05
Hi @aeris170 ,

thanks a lot for the quick review. The error is reproducible for me. Will keep you posted and release another version asap.
Thanks!

**Comment by StefanKert** [comment] 2024-05-03 15:47
Hi @aeris170,

it seems that some vs 2022 instances are registering the MS Build logger differently.  After adding another interface it is working for me and errors / warnings are correctly counted. Still not sure if this fixes it for all instances though. If you have got a few minutes to spare you can maybe do a quick check if it is also fixed for you. The new version is available in the gallery 4.0.0.10 :) thanks!

**Comment by aeris170** [comment] 2024-05-03 19:09
Hey @StefanKert 

The issue seems to be resolved on my end too. VS 2022 Version 17.9.5.

![image](https://github.com/StefanKert/BuildVision/assets/25724155/2727f8c8-ffa5-49d2-98f6-0815e0ccc19c)

**Comment by StefanKert** [comment] 2024-05-03 19:18
Perfect, thank you so much for the feedback. Going to close this issue now. If anyone is seeing other issues please create a new one. I will do a few more tests and roll out 4.0.

**Closed by StefanKert** 2024-05-03 19:18 UTC
Labels: bug, waiting-response
