### ISSUE TITLE
Failed to initialise

### ISSUE THREAD

**Issue by DrGriff** [StefanKert/BuildVision#126] opened 2023-07-20 13:17 UTC
Got this in my activity log:

![image](https://github.com/StefanKert/BuildVision/assets/19470955/236d6911-fadd-453e-83c3-52086abff445)

**Comment by alxhu-dev** [comment] 2023-09-04 19:37
Duplicate of #120

**Comment by StefanKert** [comment] 2024-04-29 05:55
Closed as duplicate #120

**Closed by StefanKert** 2024-04-29 05:55 UTC
