### ISSUE TITLE
Clicking Compiler Errors in BuildVision often do not cause jump to location

### ISSUE THREAD

**Issue by MartinL0815** [StefanKert/BuildVision#58] opened 2018-04-25 11:41 UTC
- Visual Studio Version: 14.0.25431.1
- BuildVision Version: 2.1.1.157 
- OS Version: Microsoft Windows NT 10.0.15063.0

Steps to Reproduce:

1. I build our solution
2. if errors occur while compliing, the errors are listed in the BuildVision window
3. Clicking onto the listed error, seems to be possible, since the cursor changes from the pointer to the hand
4. After clicking onto the listed error nothing happens.

I know, that it happened before.
I do not know what I did or what happend to stop it.

**Comment by StefanKert** [comment] 2018-04-30 07:08
Hey Martin! 

Thanks for reporting this. What kind of project is this? Can you share some screenshots of the errormessage you trying to click on? Thanks in advance.

**Comment by MartinL0815** [comment] 2018-06-04 09:08
Sorry, disturbance is no good companion.
After "days" of waiting for my response …

1. I am working with C++ projects.
2. The errors are some like those below:
    * ![image](https://user-images.githubusercontent.com/525700/40908149-310cceca-67e6-11e8-89a6-1738fa34c6f5.png)
    * ![image](https://user-images.githubusercontent.com/525700/40908163-3d29e1ac-67e6-11e8-9517-8646639c268b.png)
    * ![image](https://user-images.githubusercontent.com/525700/40908177-44ba8e4e-67e6-11e8-96a5-52fe4a9c1775.png)
    * 
![image](https://user-images.githubusercontent.com/525700/40908217-6320fabc-67e6-11e8-8354-f66caffa5f49.png)
    * 
![image](https://user-images.githubusercontent.com/525700/40908233-7028ad2c-67e6-11e8-8e92-1ce489cb73c4.png)

In all those cases the mouse pointer tells "you can click", but clicks do not cause jumps to the errors.

**Comment by StefanKert** [comment] 2018-06-12 07:21
I tried to reproduces this with a C++ project with the example @vladtepesch gave, but the file with the error is opening up correctly. Is it possible for one of you guys to send me a project where this "go to" is not working? Thanks!

**Comment by MartinL0815** [comment] 2018-06-12 08:32
Sorry, I'm only working with C++ projects, I cannot share with the public.
And currently I have no time to setup and test a test project

**Comment by StefanKert** [comment] 2024-05-04 05:50
Since this is not reproduceable and might be due to a specific VS version I will close this issue. Please reopen / open another one if this issue is still existent.

**Closed by StefanKert** 2024-05-04 05:50 UTC
Labels: bug
